services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VUE_APP_LOCALE=en-US
      - VUE_APP_TIMEZONE=America/Los_Angeles
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - LOCALE=en-US
      - TIMEZONE=America/Los_Angeles
