volumes:
  app-dist:

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - app-dist:/usr/src/app/dist
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - VUE_APP_LOCALE=en-US
      - VUE_APP_TIMEZONE=America/Los_Angeles
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - LOCALE=en-US
      - TIMEZONE=America/Los_Angeles
