name: "Lint Frontend"

on: [ push, pull_request, workflow_dispatch ]

jobs:
  lint:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: Lint Job
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Install Node.js dependencies
        run: |
          cd frontend &&
          npm ci

      - name: Run prettier-eslint
        run: |
          cd frontend &&
          npm run lint
