name: "Lint Frontend"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Job
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        run: |
          cd frontend &&
          npm ci

      - name: Run prettier-eslint
        run: |
          cd frontend &&
          npm run lint
